name: RSpec

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rspec:
    name: RSpec
    uses: ./.github/workflows/ruby-shared.yml
    steps:
      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec --format documentation
      - name: Upload spec log
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: spec-${{ github.run_id }}-ubuntu-latest-ruby-3.2.log
          path: spec.log
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report-${{ github.run_id }}-ubuntu-latest-ruby-3.2
          path: coverage
