name: Rubocop

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rubocop:
    name: Rubocop
    uses: ./.github/workflows/ruby-shared.yml
    steps:
      - name: Analyze code
        run: bundle exec rubocop
